# Generated by Django 3.0.8 on 2020-08-24 17:05

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Equipe',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TermsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('editor', wagtail.core.fields.RichTextField(verbose_name='Editeur')),
                ('host', wagtail.core.fields.RichTextField(verbose_name='Hébergeur')),
                ('photo_credits', wagtail.core.fields.RichTextField(verbose_name='Crédits photos')),
                ('pypo', wagtail.core.fields.RichTextField(verbose_name='Exploitant')),
                ('maker', wagtail.core.fields.RichTextField(verbose_name='Conception')),
                ('graphism', wagtail.core.fields.RichTextField(verbose_name='Graphisme')),
                ('cnil', wagtail.core.fields.RichTextField(verbose_name='CNIL')),
                ('rights', wagtail.core.fields.RichTextField(verbose_name='Propriété intellectuelle')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Accueil'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='agenda_text',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Texte agenda'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image', verbose_name='Bannière'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='playlist_text',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Texte playlist'),
        ),
        migrations.CreateModel(
            name='TeamPageMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('firstname', models.CharField(max_length=50, verbose_name='Prénom')),
                ('lastname', models.CharField(max_length=50, verbose_name='Nom')),
                ('job', models.CharField(max_length=200, verbose_name='Poste')),
                ('phone', models.CharField(max_length=15, verbose_name='Numéro')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.Image', verbose_name='Photo')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='home.TeamPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePagePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link', models.URLField(help_text='Ne garder que le lien du code                   embed, par ex. https://open.spotify.com/embed/album/***', max_length=300, null=True, verbose_name='Code embed')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssociationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.RichTextField(verbose_name='Historique')),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image', verbose_name='Bannière')),
            ],
            options={
                'verbose_name': 'Association',
            },
            bases=('wagtailcore.page',),
        ),
    ]
